version: "3.8"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./volumes/nginx/conf.d:/etc/nginx/conf.d:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
      - "3000:3000"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: aynuristica
      POSTGRES_PASSWORD: rittersport
      POSTGRES_DB: aynur-nice-try
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis:latest
    volumes:
      - ./volumes/redis/data:/data
    ports:
      - 6379:6379
